[0.08963359 0.04301965 0.03106848 0.01958062 0.01481655 0.01446388
 0.01275278 0.01104676 0.00833019 0.00717334 0.00599431 0.00560593]
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/softs/python/3.8.5/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
    r = call_item()
  File "/softs/python/3.8.5/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/softs/python/3.8.5/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/softs/python/3.8.5/lib/python3.8/site-packages/joblib/parallel.py", line 252, in __call__
    return [func(*args, **kwargs)
  File "/softs/python/3.8.5/lib/python3.8/site-packages/joblib/parallel.py", line 252, in <listcomp>
    return [func(*args, **kwargs)
  File "/softs/python/3.8.5/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 524, in _fit_and_score
    X_train, y_train = _safe_split(estimator, X, y, train)
  File "/softs/python/3.8.5/lib/python3.8/site-packages/sklearn/utils/metaestimators.py", line 198, in _safe_split
    raise ValueError("X should be a square kernel matrix")
ValueError: X should be a square kernel matrix
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "ProjetMLSVM.py", line 56, in <module>
    grid_SVC.fit(X_final, y);
  File "/softs/python/3.8.5/lib/python3.8/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
  File "/softs/python/3.8.5/lib/python3.8/site-packages/sklearn/model_selection/_search.py", line 736, in fit
    self._run_search(evaluate_candidates)
  File "/softs/python/3.8.5/lib/python3.8/site-packages/sklearn/model_selection/_search.py", line 1188, in _run_search
    evaluate_candidates(ParameterGrid(self.param_grid))
  File "/softs/python/3.8.5/lib/python3.8/site-packages/sklearn/model_selection/_search.py", line 708, in evaluate_candidates
    out = parallel(delayed(_fit_and_score)(clone(base_estimator),
  File "/softs/python/3.8.5/lib/python3.8/site-packages/joblib/parallel.py", line 1042, in __call__
    self.retrieve()
  File "/softs/python/3.8.5/lib/python3.8/site-packages/joblib/parallel.py", line 921, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/softs/python/3.8.5/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/softs/python/3.8.5/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/softs/python/3.8.5/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
ValueError: X should be a square kernel matrix
End computation
